### PR TITLE
Allow for scaling of cell sizes in discrete legend

### PR DESCRIPTION
**Pull request by slagtermaarten**
As necessary extra functionality, also implemented the ability to adjust
vertical gaps between rows (wasn't implemented at all) and horizontal
gaps between columns separately.

Sorry, my editor vim automatically converted all tabs into spaces as well. Hope this is not a problem.

### CODE REVIEW

**Comment by jokergoo** [comment]
Really sorry to reply to you after 10 months. Now I finally have time to go through your PR.

Basically, I improved the function as what you did. Thank you!

```r
lgd = Legend(labels = month.name[1:10], legend_gp = gpar(fill = 1:10), 
    title = "foo", ncol = 3, row_gap = unit(5, "mm"), column_gap = unit(5, "mm"))
```

**Comment by slagtermaarten** [comment]
Hi thanks so much for doing this. 

Although useful, this doesn't address the main feature I was trying to add. I'd like to scale cells differently in my heatmap (according to associated p-value), and therefore also create a legend with differently sized cells as a reference. Perhaps my description was too lazily written, it was included in the title. 

Could you add this feature still? Should I do it myself again, this time making sure not to affect lines I don't actually edit?

**Comment by jokergoo** [comment]
Ah, sorry I did read carefully.

Can you also send me the code which you make the heatmap where the cells sizes are different?

**Comment by slagtermaarten** [comment]
Thanks for your quick response! I used the `cell_fun` argument of `Heatmap` to scale cells using cell sizes stored in `n_cell_size_mat`. I'm additionally plotting symbols on top of the cells to indicate whether the test was statistically significant. Let me know if there's anything I can do.

```
cell_fun = function(j, i, x, y, w, h, col) {
      cs <- n_cell_size_mat[i, j]
      if (!is.na(cs) && !is.na(rc_mat[i, j])) {
        ## Sqrt transform the cell size indicator in order to get the required
        ## side length (of a square). I.e. surface area will be linearly
        ## proportional to cs
        w <- h <- cell_size * sqrt(cs)
        fill_col <- rc_col_(rc_mat[i, j])
        grid.rect(x = x, y = y,
                  width = w, height = h,
                  gp = gpar(lwd = 0, fill = fill_col, col = 'white'))
      }
      if (!is.na(icon_mat[i, j]) && icon_mat[i, j] != '') {
        if (icon_mat[i, j] == 'L') {
          l_pch = 6
        } else if (icon_mat[i, j] == 'G') {
          l_pch = 2
        }
        grid.points(x, y, pch = l_pch, size = point_size)
      }
    }
```

**Comment by jokergoo** [comment]
Aha, I see!

**Comment by slagtermaarten** [comment]
It worked fine for me, but I'm not sure this simple strategy would work as a general feature due to the user having to pre-specify the size of a full-size cell (`cell_size`), which doesn't scale with the plotting device's dimensions like this.

**Comment by jokergoo** [comment]
The current solution is to completely construct a new legend by `Legend()` function, something like:

```r
# pch = 15 is a square point
lgd = Legend(title = ..., at = ..., pch = 15, type = "points", legend_gp = gpar(size = ..., col = ...))
ht = Heatmap(..., show_heatmap_legend = FALSE) # turn off the default legend
draw(ht, heatmap_legend_list = lgd)
```

As you said, the size on the legends might not be exactly the same as in the heatmap, especially in most cases, the size of cells on heatmap depends on the size of the device. I would say, it is not easy to think of a "general" solution for this.

**Comment by slagtermaarten** [comment]
Hmm interesting, does that work for you? I'm getting the same point size throughout
Schermafbeelding 2021-02-03 om 15 26 31

**Comment by jokergoo** [comment]
Sorry, it should be the `size` that controls the size:

```r
lgd = Legend(title = "foo", at = 1:5, type = "points", pch = 15, legend_gp = gpar(col = 1:5), size = unit(1:5, "mm"))
```

image

**Comment by slagtermaarten** [comment]
Thanks!!

**Pull request closed without merging**
